### ISSUE TITLE
TransformerBlock

### ISSUE THREAD

**Issue by rpraver** [AmirAbaskohi/Transformers-Tutorial#1]
The decoder is using 'TransformerBlock' and it is not defined? Have you attempted to execute main? There are other issues where you have not imported torch.nn.

**Comment by AmirAbaskohi** [comment]
Thanks for letting me know. I will try to fix the issues.
In case you want to make any changes, just create a pull a request.

**Comment by rpraver** [comment]
Thanx, for your response.
